#Compiler and flags
CC = gcc
CFLAGS = -Wall -std=c99

#inlcude files directory
INCLUDES = -Iinclude

#Directories with source code, object files and binary
SRCDIR = ./
BINDIR = bin/

PROGNAME = main


all: P11 P12

P11 : P11.c

P12: P12.c

clean:
	@rm *.o P11 P12